# LuaJIT Azure Piplines build script
jobs:
- job: Windows_Build
  pool:
    vmImage: windows-2019

  strategy:
    maxParallel: 3
    matrix:
      Win_x86:
        VC_ARCH: x86
        buildMode:
      Win_x64:
        VC_ARCH: amd64
        buildMode:
      Win_x64_GC64:
        VC_ARCH: amd64
        buildMode: gc64
  steps:
  - template: ./windows.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    maxParallel: 3
    matrix:
      Linux_x64:
        buildFlags:
      Linux_x64_GC64:
        buildFlags: -DLUAJIT_ENABLE_GC64
  steps:
  - template: ./linux.yml
